/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedPredictionsRouteImport } from './routes/_protected/predictions'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as AuthCallbackGoogleRouteImport } from './routes/auth/callback/google'
import { Route as ProtectedTeamTeamIdRouteImport } from './routes/_protected/team/$teamId'
import { Route as ProtectedAdminGroupIdRouteImport } from './routes/_protected/admin/$groupId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPredictionsRoute = ProtectedPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthCallbackGoogleRoute = AuthCallbackGoogleRouteImport.update({
  id: '/auth/callback/google',
  path: '/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTeamTeamIdRoute = ProtectedTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminGroupIdRoute = ProtectedAdminGroupIdRouteImport.update({
  id: '/admin/$groupId',
  path: '/admin/$groupId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/superadmin': typeof SuperadminRoute
  '/terms': typeof TermsRoute
  '/predictions': typeof ProtectedPredictionsRoute
  '/profile': typeof ProtectedProfileRoute
  '/admin/$groupId': typeof ProtectedAdminGroupIdRoute
  '/team/$teamId': typeof ProtectedTeamTeamIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/superadmin': typeof SuperadminRoute
  '/terms': typeof TermsRoute
  '/predictions': typeof ProtectedPredictionsRoute
  '/profile': typeof ProtectedProfileRoute
  '/': typeof ProtectedIndexRoute
  '/admin/$groupId': typeof ProtectedAdminGroupIdRoute
  '/team/$teamId': typeof ProtectedTeamTeamIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/superadmin': typeof SuperadminRoute
  '/terms': typeof TermsRoute
  '/_protected/predictions': typeof ProtectedPredictionsRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/admin/$groupId': typeof ProtectedAdminGroupIdRoute
  '/_protected/team/$teamId': typeof ProtectedTeamTeamIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy-policy'
    | '/superadmin'
    | '/terms'
    | '/predictions'
    | '/profile'
    | '/admin/$groupId'
    | '/team/$teamId'
    | '/auth/callback/google'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy-policy'
    | '/superadmin'
    | '/terms'
    | '/predictions'
    | '/profile'
    | '/'
    | '/admin/$groupId'
    | '/team/$teamId'
    | '/auth/callback/google'
    | '/admin'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/privacy-policy'
    | '/superadmin'
    | '/terms'
    | '/_protected/predictions'
    | '/_protected/profile'
    | '/_protected/'
    | '/_protected/admin/$groupId'
    | '/_protected/team/$teamId'
    | '/auth/callback/google'
    | '/_protected/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SuperadminRoute: typeof SuperadminRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackGoogleRoute: typeof AuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/predictions': {
      id: '/_protected/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof ProtectedPredictionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/callback/google': {
      id: '/auth/callback/google'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/team/$teamId': {
      id: '/_protected/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof ProtectedTeamTeamIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/$groupId': {
      id: '/_protected/admin/$groupId'
      path: '/admin/$groupId'
      fullPath: '/admin/$groupId'
      preLoaderRoute: typeof ProtectedAdminGroupIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedPredictionsRoute: typeof ProtectedPredictionsRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedAdminGroupIdRoute: typeof ProtectedAdminGroupIdRoute
  ProtectedTeamTeamIdRoute: typeof ProtectedTeamTeamIdRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedPredictionsRoute: ProtectedPredictionsRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedAdminGroupIdRoute: ProtectedAdminGroupIdRoute,
  ProtectedTeamTeamIdRoute: ProtectedTeamTeamIdRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SuperadminRoute: SuperadminRoute,
  TermsRoute: TermsRoute,
  AuthCallbackGoogleRoute: AuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
